services:
  # Service PHP pour exécuter Symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/project
    volumes:
      - .:/var/www/project
    depends_on:
      - db

  # Service Nginx pour servir l'application
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/project
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # Service MySQL pour la base de données
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql

  # (Optionnel) Service Adminer pour gérer la base de données via une interface web
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

# Volumes pour persister les données
volumes:
  db_data:
